language: android
os:
  - linux
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2
android:
  components:
    - sys-img-armeabi-v7a-android-21
    - build-tools-22.0.1
    - build-tools-23.0.1
    - platform-tools
    - tools
    - extra
# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
script:
  - curl -o sbt-launcher.sh https://raw.githubusercontent.com/paulp/sbt-extras/master/sbt
  - chmod a+x ./sbt-launcher.sh
  - ./sbt-launcher.sh compile scripted