language: android
sudo: required
os:
  - linux
jdk:
  - oraclejdk8

env:
  global:
    - NDK_VERSION=r11c
    - ANDROID_NDK_HOME=$HOME/android-ndk-$NDK_VERSION
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2
android:
  components:
    - sys-img-armeabi-v7a-android-24
    - platform-tools
    - build-tools-26.0.1
    - android-24
    - tools
    - extra
before_script:
  # Emulator Management: Create, Start and Wait
  - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  # install & cache NDK
  - curl https://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-linux-x86_64.zip -z ${ANDROID_NDK_HOME}/ndk-build -o $HOME/ndk-${NDK_VERSION}.zip
  - (unzip -q $HOME/ndk-$NDK_VERSION.zip -d $HOME; true)
  - ls $ANDROID_NDK_HOME
  # wait for emulator after ndk
  - adb shell input keyevent 82 &
script:
  - curl -o sbt-launcher.sh https://raw.githubusercontent.com/paulp/sbt-extras/master/sbt
  - chmod a+x ./sbt-launcher.sh
  - ./sbt-launcher.sh publish-local
  - ./sbt-launcher.sh gradlebuild/publish-local
  - android-wait-for-emulator
  - ./sbt-launcher.sh "scripted android-sdk-plugin/* gradle-build/*"
